# _config.yml - Basic Boilerplate
# Site settings
baseurl: "" # Leave blank for the root
url: "https://psharp725.github.io" 
title: "Patrick's Personal Website"
description: "Welcome to Patrick's personal website."
author: "Patrick Sharp"

# Markdown options
markdown: kramdown
highlighter: rouge

theme: minima # A simple Jekyll theme
plugins:
  - jekyll-feed # Optional RSS feed plugin
