title: "Patrick Sharp's Personal Website"
description: "Welcome to My Personal Website"
author: "Patrick Sharp"

remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

kramdown:
  syntax_highlighter_opts:
    disable: true

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other

keep_files:
  - assets/LeetCode/
