# Site settings
title: "Patrick Sharp"
tagline: "Portfolio and Projects"
description: "Showcasing my work, experience, and projects."
url: "https://psharp725.github.io" # Update this with your GitHub Pages URL
baseurl: "" # Leave blank unless hosting in a subdirectory

# Theme settings
remote_theme: "cotes2020/jekyll-theme-chirpy" # Chirpy theme
timezone: America/Denver
lang: en

# Navigation: Define only the pages you want in the header
header_pages:
  - index.md
  - resume.md
  - ProjectProposal.md
  - LeetCode.md

# Exclude unwanted files from the site
exclude:
  - "assets/LeetCode/*"    # Hide LeetCode assets
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"

# Social Links (update these with your actual links)
social:
  github: PSharp725
  linkedin: patrick-sharp-278123191
  email: PatrickSharp725@gmail.com

# Enable search
search: true

# Enable syntax highlighting for code
kramdown:
  syntax_highlighter_opts:
    disable: false

