# _config.yml - Basic Boilerplate
# Site settings
baseurl: "" 
url: "https://psharp725.github.io" 
title: "Patrick Sharp's Personal Website"
description: "Welcome to My Personal Website"
author: "Patrick Sharp"

# Markdown options
markdown: kramdown
highlighter: rouge

theme: minima 
#plugins:
#  - jekyll-feed # Optional RSS feed plugin

