# _config.yml - Basic Boilerplate for Minimal Mistakes
title: "Patrick Sharp's Personal Website"
description: "Welcome to My Personal Website"
author: "Patrick Sharp"

theme: "minimal-mistakes-jekyll"

plugins:
  - jekyll-feed
  - jekyll-sitemap

kramdown:
  syntax_highlighter_opts:
    disable: true

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other


