# _config.yml - Basic Boilerplate
# Site settings
baseurl: "" # Leave blank for the root
url: "https://psharp725.github.io" 
title: "About Me"
description: "Welcome to My Personal Website"
author: "Patrick Sharp"

# Markdown options
markdown: kramdown
highlighter: rouge

theme: jekyll-theme-minimal  # A simple Jekyll theme
plugins:
  - jekyll-feed # Optional RSS feed plugin


  # Navigation settings (optional)
nav_links:
  - name: "About Me"
    link: "/"
  - name: "Resume"
    link: "/resume/"
